# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignedto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'assignedto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('cname', models.CharField(db_column='cName', max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'crime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestigationRelatesto',
            fields=[
                ('inumber', models.IntegerField(db_column='iNumber', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'investigation_relatesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfficerEmployedby',
            fields=[
                ('badgenum', models.IntegerField(db_column='badgeNum', primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'officer_employedby',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('pname', models.CharField(db_column='pName', max_length=30, primary_key=True, serialize=False)),
                ('phonenum', models.CharField(blank=True, db_column='phoneNum', max_length=12, null=True, unique=True)),
            ],
            options={
                'db_table': 'precinct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportReportsonFiles',
            fields=[
                ('reportnum', models.IntegerField(db_column='reportNum', primary_key=True, serialize=False)),
                ('cdatetime', models.DateTimeField(blank=True, db_column='cDatetime', null=True)),
                ('caddress', models.CharField(blank=True, db_column='cAddress', max_length=60, null=True)),
                ('cdescription', models.CharField(blank=True, db_column='cDescription', max_length=500, null=True)),
            ],
            options={
                'db_table': 'report_reportson_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusHasstatusHasoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'status_hasstatus_hasoption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statusoption',
            fields=[
                ('soname', models.CharField(db_column='soName', max_length=60, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'statusoption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuspectIson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'suspect_ison',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('ssn', models.ForeignKey(db_column='ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Person')),
            ],
            options={
                'db_table': 'detective',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ssn', models.ForeignKey(db_column='ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.Person')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workson',
            fields=[
                ('reportnum', models.ForeignKey(db_column='reportNum', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.ReportReportsonFiles')),
            ],
            options={
                'db_table': 'workson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('ssn', models.ForeignKey(db_column='ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.User')),
            ],
            options={
                'db_table': 'clerk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardUser',
            fields=[
                ('ssn', models.ForeignKey(db_column='ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='search.User')),
            ],
            options={
                'db_table': 'standard_user',
                'managed': False,
            },
        ),
    ]
